### ISSUE TITLE
[求助]请问能否将签到的图片尺寸限定在1280x1280以内

### ISSUE THREAD

**Issue by ultimatepasserby** [FrostN0v0/nonebot-plugin-pcr-sign#2]
因为tg的bot发送照片时请求最大尺寸为1280 × 1280 像素，不然的话...
![image](https://github.com/user-attachments/assets/93760600-53ed-46bb-b25c-195d0bd1d37f)

~~不行，这...这个...太大了~~

（收集册的图片长宽都在1280px以内所以能正常发送）

**Comment by FrostN0v0** [comment]
未能成功复现报错，可以留个联系方式，沟通复现一下，个人没用过tg的bot，不是很熟。 @ultimatepasserby

**Comment by FrostN0v0** [comment]
![image](https://github.com/user-attachments/assets/c0a7dcab-e7e5-46c5-bc74-03f586872d0a)

~~好像一般超不出这个限制？~~
不过在tg测了下， msg_id的获取确实有问题，藏不了暗语，修一下

**Comment by FrostN0v0** [comment]
啊啊，复现出来了，我一开始用的图源是loliapi，这个可能不是图片尺寸问题，是图片文件太大了，我想办法压缩一下，10M的大小限制。
~~为什么塞那么大的背景图啊喂~~

**Comment by FrostN0v0** [comment]
修好了，请安装最新版使用 @ultimatepasserby 
顺便把暗语也修了，自测没什么问题。
![ae4a839523452e1e6857438248046b6](https://github.com/user-attachments/assets/5c2f94c2-d125-4e34-8b2e-79fac530e8cb)
